### ISSUE TITLE
Crash if search opened before backup data is read

### ISSUE THREAD

**Issue by lightonflux** [jensstein/oandbackup#76] opened 2015-01-05 12:37 UTC
If you press the search button immediately after the start of oab, before the program can collect data of the backups, then the program crashes.

**Comment by jensstein** [comment] 2015-01-05 13:04
this is a duplicate of this report: https://github.com/jensstein/oandbackup/issues/60
it was fixed right after the latest release but it will be there in the next one.
thanks for reporting anyway :)

**Closed by jensstein** 2015-01-05 13:04 UTC
