### ISSUE TITLE
Reload of AppList on Device-Rotate

### ISSUE THREAD

**Issue by DJaeger** [jensstein/oandbackup#92] opened 2015-03-16 12:56 UTC
The AppList reloads on every orientation change of the device.
It requests every time the superuser right and seems to completely rebuild the list, not only the rendering.

**Comment by jensstein** [comment] 2015-03-19 10:52
you're right. thanks for reporting.
i had forgotten about the call to get a list of users on the device which uses su.
that the list looked like it was being rebuilt was just because of a lag caused by the program handling su, i think.
this is fixed with commit a802b9348a8ff727f81af9d0773d7f1a95a5c118.

**Closed by jensstein** 2015-03-19 10:52 UTC
